-- ╭──────────────────────────────────────────────────────────────────────────╮
-- │ 027 — Baseline: bisher undokumentierte Tabellen (Source-of-Truth-Sync)    │
-- │                                                                            │
-- │ Diese Tabellen existierten live (Projekt rcqichlyllhwougopfkg), waren aber │
-- │ nie als Migration eingecheckt (per Dashboard/ad-hoc angelegt). Ohne sie    │
-- │ liefen RLS-Audits gegen die Migrations ins Leere. Aus dem Live-Katalog     │
-- │ rekonstruiert. Vollständig idempotent (create … if not exists / drop       │
-- │ policy if exists) → No-Op auf der bestehenden DB, baut auf einer frischen  │
-- │ DB korrekt auf. Reihenfolge nach FK-Abhängigkeit.                          │
-- ╰──────────────────────────────────────────────────────────────────────────╯

-- ── Tabellen ─────────────────────────────────────────────────────────────────

create table if not exists ambassadors (
  id uuid not null default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  community_region text,
  notes text,
  status text not null default 'active'::text,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint ambassadors_pkey primary key (id),
  constraint ambassadors_created_by_fkey foreign key (created_by) references profiles(id) on delete set null,
  constraint ambassadors_status_check check (status = any (array['active','inactive','blocked']))
);

create table if not exists awards (
  id uuid not null default gen_random_uuid(),
  tournament_id uuid not null,
  award_type text not null,
  title text not null,
  description text,
  recipient_profile_id uuid,
  recipient_name text,
  recipient_team text,
  created_at timestamptz default now(),
  constraint awards_pkey primary key (id),
  constraint awards_tournament_id_fkey foreign key (tournament_id) references tournaments(id) on delete cascade,
  constraint awards_recipient_profile_id_fkey foreign key (recipient_profile_id) references profiles(id) on delete set null,
  constraint awards_award_type_check check (award_type = any (array['champion','runner_up','longest_drive','closest_to_pin','mvp','rivalry','custom'])),
  constraint awards_recipient_team_check check ((recipient_team = any (array['A','B'])) or (recipient_team is null))
);

create table if not exists challenges (
  id uuid not null default uuid_generate_v4(),
  challenger_id uuid not null,
  opponent_id uuid,
  challenger_team uuid[] default '{}'::uuid[],
  opponent_team uuid[] default '{}'::uuid[],
  type text not null,
  title text not null,
  description text,
  stake text,
  visibility text not null default 'friends'::text,
  status text not null default 'pending'::text,
  tournament_id uuid,
  match_id uuid,
  winner_side text,
  dealbuddy_url text,
  created_at timestamptz default now(),
  accepted_at timestamptz,
  finished_at timestamptz,
  constraint challenges_pkey primary key (id),
  constraint challenges_challenger_id_fkey foreign key (challenger_id) references profiles(id) on delete cascade,
  constraint challenges_opponent_id_fkey foreign key (opponent_id) references profiles(id) on delete set null,
  constraint challenges_tournament_id_fkey foreign key (tournament_id) references tournaments(id) on delete set null,
  constraint challenges_match_id_fkey foreign key (match_id) references matches(id) on delete set null,
  constraint challenges_type_check check (type = any (array['singles','doubles','team'])),
  constraint challenges_visibility_check check (visibility = any (array['public','friends','private'])),
  constraint challenges_status_check check (status = any (array['pending','accepted','declined','active','finished','cancelled'])),
  constraint challenges_winner_side_check check (winner_side = any (array['challenger','opponent','halved']))
);

create table if not exists client_debug (
  id bigint generated by default as identity,
  created_at timestamptz default now(),
  session_id text,
  user_id uuid,
  event text not null,
  payload jsonb not null default '{}'::jsonb,
  user_agent text,
  constraint client_debug_pkey primary key (id)
);

create table if not exists community_groups (
  id uuid not null default gen_random_uuid(),
  name text not null,
  slug text not null,
  description text,
  cover_url text,
  region text,
  type text default 'crew'::text,
  owner_id uuid,
  visibility text not null default 'public'::text,
  created_at timestamptz not null default now(),
  constraint community_groups_pkey primary key (id),
  constraint community_groups_slug_key unique (slug),
  constraint community_groups_owner_id_fkey foreign key (owner_id) references profiles(id) on delete set null,
  constraint community_groups_type_check check (type = any (array['crew','club','company','city'])),
  constraint community_groups_visibility_check check (visibility = any (array['public','private','invite_only']))
);

create table if not exists community_group_members (
  id uuid not null default gen_random_uuid(),
  group_id uuid not null,
  profile_id uuid not null,
  role text not null default 'member'::text,
  joined_at timestamptz not null default now(),
  constraint community_group_members_pkey primary key (id),
  constraint community_group_members_group_id_profile_id_key unique (group_id, profile_id),
  constraint community_group_members_group_id_fkey foreign key (group_id) references community_groups(id) on delete cascade,
  constraint community_group_members_profile_id_fkey foreign key (profile_id) references profiles(id) on delete cascade,
  constraint community_group_members_role_check check (role = any (array['captain','member','guest']))
);

create table if not exists courses (
  id uuid not null default uuid_generate_v4(),
  source text not null default 'user'::text,
  source_id text,
  name text not null,
  city text,
  country text,
  postal_code text,
  lat double precision,
  lng double precision,
  geom geography(Point,4326),
  hole_pars integer[] default '{}'::integer[],
  hole_handicaps integer[] default '{}'::integer[],
  total_par integer,
  num_holes integer default 18,
  notes text,
  created_by uuid,
  last_edited_by uuid,
  last_edited_at timestamptz,
  contributor_count integer default 0,
  created_at timestamptz default now(),
  website text,
  scorecard_source_url text,
  scorecard_scraped_at timestamptz,
  scorecard_scrape_status text,
  constraint courses_pkey primary key (id),
  constraint courses_created_by_fkey foreign key (created_by) references profiles(id) on delete set null,
  constraint courses_last_edited_by_fkey foreign key (last_edited_by) references profiles(id) on delete set null,
  constraint courses_source_check check (source = any (array['user','golfcourseapi','osm','import']))
);

create table if not exists course_edits (
  id uuid not null default uuid_generate_v4(),
  course_id uuid not null,
  edited_by uuid,
  hole_pars integer[],
  hole_handicaps integer[],
  source_match_id uuid,
  created_at timestamptz default now(),
  constraint course_edits_pkey primary key (id),
  constraint course_edits_course_id_fkey foreign key (course_id) references courses(id) on delete cascade,
  constraint course_edits_edited_by_fkey foreign key (edited_by) references profiles(id) on delete set null,
  constraint course_edits_source_match_id_fkey foreign key (source_match_id) references matches(id) on delete set null
);

create table if not exists event_ambassadors (
  id uuid not null default gen_random_uuid(),
  tournament_id uuid not null,
  ambassador_id uuid not null,
  partner_role text not null,
  commission_rate numeric(4,2) not null,
  revenue_gross numeric(12,2) not null default 0,
  direct_event_costs numeric(12,2) not null default 0,
  operating_contribution numeric(12,2) generated always as (revenue_gross - direct_event_costs) stored,
  commission_amount numeric(12,2),
  contribution_description text,
  claim_valid_until date,
  approval_status text not null default 'draft'::text,
  approved_by uuid,
  approved_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  constraint event_ambassadors_pkey primary key (id),
  constraint event_ambassadors_tournament_id_fkey foreign key (tournament_id) references tournaments(id) on delete cascade,
  constraint event_ambassadors_ambassador_id_fkey foreign key (ambassador_id) references ambassadors(id) on delete cascade,
  constraint event_ambassadors_approved_by_fkey foreign key (approved_by) references profiles(id) on delete set null,
  constraint event_ambassadors_partner_role_check check (partner_role = any (array['connector','host_partner','operating_partner','renewal_passive','renewal_active'])),
  constraint event_ambassadors_approval_status_check check (approval_status = any (array['draft','pending_review','approved','rejected','paid'])),
  constraint event_ambassadors_commission_rate_check check (commission_rate >= 0 and commission_rate <= 100)
);

create table if not exists newsletter_subscribers (
  id uuid not null default gen_random_uuid(),
  email text not null,
  lang text default 'en'::text,
  source text,
  status text not null default 'pending'::text,
  confirm_token text not null,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  unsubscribed_at timestamptz,
  constraint newsletter_subscribers_pkey primary key (id),
  constraint newsletter_subscribers_email_key unique (email),
  constraint newsletter_subscribers_status_check check (status = any (array['pending','confirmed','unsubscribed']))
);

create table if not exists premium_purchases (
  id uuid not null default gen_random_uuid(),
  tournament_id uuid not null,
  buyer_profile_id uuid,
  package_type text not null default 'premium'::text,
  amount_eur_cents integer not null,
  currency text not null default 'eur'::text,
  stripe_session_id text,
  stripe_payment_intent_id text,
  stripe_checkout_url text,
  status text not null default 'pending'::text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  metadata jsonb default '{}'::jsonb,
  constraint premium_purchases_pkey primary key (id),
  constraint premium_purchases_stripe_session_id_key unique (stripe_session_id),
  constraint premium_purchases_tournament_id_fkey foreign key (tournament_id) references tournaments(id) on delete cascade,
  constraint premium_purchases_buyer_profile_id_fkey foreign key (buyer_profile_id) references profiles(id) on delete set null,
  constraint premium_purchases_package_type_check check (package_type = any (array['premium','club','league'])),
  constraint premium_purchases_status_check check (status = any (array['pending','paid','refunded','failed']))
);

create table if not exists private_config (
  key text not null,
  value text not null,
  constraint private_config_pkey primary key (key)
);

create table if not exists referrals (
  id uuid not null default gen_random_uuid(),
  inviter_id uuid not null,
  invitee_id uuid not null,
  ref_code text not null,
  status text not null default 'pending'::text,
  created_at timestamptz not null default now(),
  converted_at timestamptz,
  constraint referrals_pkey primary key (id),
  constraint referrals_invitee_id_key unique (invitee_id),
  constraint referrals_inviter_id_fkey foreign key (inviter_id) references profiles(id) on delete cascade,
  constraint referrals_invitee_id_fkey foreign key (invitee_id) references profiles(id) on delete cascade,
  constraint referrals_status_check check (status = any (array['pending','converted','revoked']))
);

create table if not exists savor_partners (
  id uuid not null default gen_random_uuid(),
  name text not null,
  slug text,
  type text default 'partner'::text,
  logo_url text,
  website_url text,
  city text,
  country_code text,
  description text,
  contact_email text,
  status text not null default 'active'::text,
  created_at timestamptz not null default now(),
  constraint savor_partners_pkey primary key (id),
  constraint savor_partners_slug_key unique (slug),
  constraint savor_partners_type_check check (type = any (array['partner','club','restaurant','travel_op','brand','pro_shop'])),
  constraint savor_partners_status_check check (status = any (array['active','paused','blocked']))
);

create table if not exists savor_offers (
  id uuid not null default gen_random_uuid(),
  category text not null,
  title text not null,
  slug text,
  subtitle text,
  description text,
  image_url text,
  city text,
  country_code text,
  partner_id uuid,
  price_eur_cents integer,
  price_label text,
  currency text default 'eur'::text,
  external_url text,
  available_from date,
  available_until date,
  tee_time_at timestamptz,
  highlight boolean default false,
  badge text,
  sort_order integer default 0,
  status text not null default 'active'::text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint savor_offers_pkey primary key (id),
  constraint savor_offers_slug_key unique (slug),
  constraint savor_offers_partner_id_fkey foreign key (partner_id) references savor_partners(id) on delete set null,
  constraint savor_offers_category_check check (category = any (array['tee_times','experiences','dining','apparel','travel','equipment'])),
  constraint savor_offers_status_check check (status = any (array['active','sold_out','draft','archived']))
);

create table if not exists savor_wishlist (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  offer_id uuid not null,
  created_at timestamptz not null default now(),
  constraint savor_wishlist_pkey primary key (id),
  constraint savor_wishlist_user_id_offer_id_key unique (user_id, offer_id),
  constraint savor_wishlist_user_id_fkey foreign key (user_id) references profiles(id) on delete cascade,
  constraint savor_wishlist_offer_id_fkey foreign key (offer_id) references savor_offers(id) on delete cascade
);

create table if not exists seasons (
  id uuid not null default gen_random_uuid(),
  group_id uuid,
  name text not null,
  slug text not null,
  starts_on date,
  ends_on date,
  type text default 'season'::text,
  cover_url text,
  description text,
  owner_id uuid,
  visibility text not null default 'public'::text,
  scoring text default 'cups_won'::text,
  created_at timestamptz not null default now(),
  constraint seasons_pkey primary key (id),
  constraint seasons_slug_key unique (slug),
  constraint seasons_group_id_fkey foreign key (group_id) references community_groups(id) on delete cascade,
  constraint seasons_owner_id_fkey foreign key (owner_id) references profiles(id) on delete set null,
  constraint seasons_type_check check (type = any (array['season','league','city_rivalry','tour'])),
  constraint seasons_visibility_check check (visibility = any (array['public','private'])),
  constraint seasons_scoring_check check (scoring = any (array['cups_won','points','aggregate']))
);

create table if not exists sponsors (
  id uuid not null default gen_random_uuid(),
  name text not null,
  logo_url text,
  website_url text,
  contact_email text,
  type text default 'partner'::text,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint sponsors_pkey primary key (id),
  constraint sponsors_created_by_fkey foreign key (created_by) references profiles(id) on delete set null,
  constraint sponsors_type_check check (type = any (array['partner','sponsor','venue','equipment','custom']))
);

create table if not exists sponsor_placements (
  id uuid not null default gen_random_uuid(),
  tournament_id uuid not null,
  sponsor_id uuid not null,
  placement_type text not null default 'powered_by'::text,
  status text not null default 'active'::text,
  created_at timestamptz not null default now(),
  constraint sponsor_placements_pkey primary key (id),
  constraint sponsor_placements_tournament_id_sponsor_id_placement_type_key unique (tournament_id, sponsor_id, placement_type),
  constraint sponsor_placements_tournament_id_fkey foreign key (tournament_id) references tournaments(id) on delete cascade,
  constraint sponsor_placements_sponsor_id_fkey foreign key (sponsor_id) references sponsors(id) on delete cascade,
  constraint sponsor_placements_placement_type_check check (placement_type = any (array['powered_by','title_sponsor','award_sponsor'])),
  constraint sponsor_placements_status_check check (status = any (array['active','removed']))
);

-- ── Helper-Funktion (von challenges_read benötigt) ───────────────────────────

create or replace function can_view_challenge(c_id uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from challenges c
    where c.id = c_id
      and (
        c.visibility = 'public'
        or c.challenger_id = auth.uid()
        or c.opponent_id   = auth.uid()
        or auth.uid() = any(c.challenger_team)
        or auth.uid() = any(c.opponent_team)
        or (c.visibility = 'friends' and (
            are_friends(auth.uid(), c.challenger_id)
            or (c.opponent_id is not null and are_friends(auth.uid(), c.opponent_id))
        ))
      )
  );
$$;

-- ── Indizes ──────────────────────────────────────────────────────────────────

create index if not exists ambassadors_status_idx on ambassadors (status);
create index if not exists awards_tournament_idx on awards (tournament_id);
create index if not exists challenges_challenger_idx on challenges (challenger_id);
create index if not exists challenges_opponent_idx on challenges (opponent_id);
create index if not exists challenges_status_idx on challenges (status);
create index if not exists challenges_visibility_idx on challenges (visibility);
create index if not exists client_debug_created_idx on client_debug (created_at desc);
create index if not exists client_debug_session_idx on client_debug (session_id, created_at);
create index if not exists community_groups_owner_idx on community_groups (owner_id);
create index if not exists community_groups_slug_idx on community_groups (slug);
create index if not exists course_edits_course_idx on course_edits (course_id, created_at desc);
create unique index if not exists courses_source_uniq on courses (source, source_id) where (source_id is not null);
create index if not exists courses_name_trgm on courses using gin (lower(name) gin_trgm_ops);
create index if not exists courses_geom_idx on courses using gist (geom);
create index if not exists courses_country_idx on courses (country);
create index if not exists event_ambassadors_tournament_idx on event_ambassadors (tournament_id);
create index if not exists event_ambassadors_ambassador_idx on event_ambassadors (ambassador_id);
create index if not exists event_ambassadors_status_idx on event_ambassadors (approval_status);
create index if not exists idx_newsletter_status on newsletter_subscribers (status);
create index if not exists premium_purchases_tournament_idx on premium_purchases (tournament_id);
create index if not exists premium_purchases_status_idx on premium_purchases (status);
create index if not exists idx_referrals_inviter on referrals (inviter_id);
create index if not exists idx_referrals_invitee on referrals (invitee_id);
create index if not exists savor_offers_cat_idx on savor_offers (category, status, sort_order);
create index if not exists savor_offers_highlight_idx on savor_offers (highlight) where (highlight = true);
create index if not exists savor_offers_city_idx on savor_offers (city);
create index if not exists savor_offers_tee_at_idx on savor_offers (tee_time_at) where (tee_time_at is not null);
create index if not exists sponsor_placements_tournament_idx on sponsor_placements (tournament_id);

-- ── RLS aktivieren ───────────────────────────────────────────────────────────

alter table ambassadors             enable row level security;
alter table awards                  enable row level security;
alter table challenges              enable row level security;
alter table client_debug            enable row level security;
alter table community_groups        enable row level security;
alter table community_group_members enable row level security;
alter table courses                 enable row level security;
alter table course_edits            enable row level security;
alter table event_ambassadors       enable row level security;
alter table premium_purchases       enable row level security;
alter table referrals               enable row level security;
alter table savor_offers            enable row level security;
alter table savor_partners          enable row level security;
alter table savor_wishlist          enable row level security;
alter table seasons                 enable row level security;
alter table sponsors                enable row level security;
alter table sponsor_placements      enable row level security;

-- ── Policies ─────────────────────────────────────────────────────────────────

drop policy if exists ambassadors_admin_all on ambassadors;
create policy ambassadors_admin_all on ambassadors for all
  using ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de')
  with check ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de');

drop policy if exists awards_select on awards;
create policy awards_select on awards for select using (exists (
  select 1 from tournaments t where t.id = awards.tournament_id
    and (t.visibility = 'public' or t.owner_id = auth.uid())));
drop policy if exists awards_insert on awards;
create policy awards_insert on awards for insert with check (exists (
  select 1 from tournaments t where t.id = awards.tournament_id and t.owner_id = auth.uid()));
drop policy if exists awards_update on awards;
create policy awards_update on awards for update using (exists (
  select 1 from tournaments t where t.id = awards.tournament_id and t.owner_id = auth.uid()));
drop policy if exists awards_delete on awards;
create policy awards_delete on awards for delete using (exists (
  select 1 from tournaments t where t.id = awards.tournament_id and t.owner_id = auth.uid()));

drop policy if exists challenges_read on challenges;
create policy challenges_read on challenges for select using (can_view_challenge(id));
drop policy if exists challenges_insert on challenges;
create policy challenges_insert on challenges for insert with check (challenger_id = auth.uid());
drop policy if exists challenges_update on challenges;
create policy challenges_update on challenges for update using (
  challenger_id = auth.uid() or opponent_id = auth.uid()
  or auth.uid() = any (challenger_team) or auth.uid() = any (opponent_team));
drop policy if exists challenges_delete on challenges;
create policy challenges_delete on challenges for delete using (challenger_id = auth.uid());

drop policy if exists client_debug_insert_anyone on client_debug;
create policy client_debug_insert_anyone on client_debug for insert with check (true);
drop policy if exists client_debug_select_none on client_debug;
create policy client_debug_select_none on client_debug for select using (false);

drop policy if exists groups_select_public on community_groups;
create policy groups_select_public on community_groups for select using (
  visibility = 'public' or owner_id = auth.uid()
  or exists (select 1 from community_group_members m where m.group_id = m.id and m.profile_id = auth.uid()));
drop policy if exists groups_insert_self on community_groups;
create policy groups_insert_self on community_groups for insert with check (owner_id = auth.uid());
drop policy if exists groups_update_owner on community_groups;
create policy groups_update_owner on community_groups for update using (owner_id = auth.uid());
drop policy if exists groups_delete_owner on community_groups;
create policy groups_delete_owner on community_groups for delete using (owner_id = auth.uid());

drop policy if exists members_select_any on community_group_members;
create policy members_select_any on community_group_members for select using (exists (
  select 1 from community_groups g where g.id = community_group_members.group_id
    and (g.visibility = 'public' or g.owner_id = auth.uid() or community_group_members.profile_id = auth.uid())));
drop policy if exists members_join_self on community_group_members;
create policy members_join_self on community_group_members for insert with check (profile_id = auth.uid());
drop policy if exists members_modify_owner on community_group_members;
create policy members_modify_owner on community_group_members for update using (exists (
  select 1 from community_groups g where g.id = community_group_members.group_id and g.owner_id = auth.uid()));
drop policy if exists members_delete_owner_or_self on community_group_members;
create policy members_delete_owner_or_self on community_group_members for delete using (
  profile_id = auth.uid() or exists (
    select 1 from community_groups g where g.id = community_group_members.group_id and g.owner_id = auth.uid()));

drop policy if exists courses_read on courses;
create policy courses_read on courses for select using (true);
drop policy if exists courses_insert on courses;
create policy courses_insert on courses for insert with check (auth.uid() is not null);
drop policy if exists courses_update on courses;
create policy courses_update on courses for update using (auth.uid() is not null);

drop policy if exists course_edits_read on course_edits;
create policy course_edits_read on course_edits for select using (true);
drop policy if exists course_edits_insert on course_edits;
create policy course_edits_insert on course_edits for insert with check (edited_by = auth.uid());

drop policy if exists event_ambassadors_admin_all on event_ambassadors;
create policy event_ambassadors_admin_all on event_ambassadors for all
  using ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de')
  with check ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de');

drop policy if exists premium_select_owner on premium_purchases;
create policy premium_select_owner on premium_purchases for select using (exists (
  select 1 from tournaments t where t.id = premium_purchases.tournament_id and t.owner_id = auth.uid()));
drop policy if exists premium_insert_owner on premium_purchases;
create policy premium_insert_owner on premium_purchases for insert with check (exists (
  select 1 from tournaments t where t.id = premium_purchases.tournament_id and t.owner_id = auth.uid()));

drop policy if exists referrals_select_own on referrals;
create policy referrals_select_own on referrals for select using (
  auth.uid() = inviter_id or auth.uid() = invitee_id);

drop policy if exists savor_offers_select_active on savor_offers;
create policy savor_offers_select_active on savor_offers for select using (status = any (array['active','sold_out']));
drop policy if exists savor_offers_admin_write on savor_offers;
create policy savor_offers_admin_write on savor_offers for all
  using ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de')
  with check ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de');

drop policy if exists savor_partners_select_any on savor_partners;
create policy savor_partners_select_any on savor_partners for select using (status = 'active');
drop policy if exists savor_partners_admin_write on savor_partners;
create policy savor_partners_admin_write on savor_partners for all
  using ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de')
  with check ((auth.jwt() ->> 'email') = 'rainer.roloff@comms-connect.de');

drop policy if exists savor_wishlist_self_all on savor_wishlist;
create policy savor_wishlist_self_all on savor_wishlist for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists seasons_select_public on seasons;
create policy seasons_select_public on seasons for select using (visibility = 'public' or owner_id = auth.uid());
drop policy if exists seasons_insert_self on seasons;
create policy seasons_insert_self on seasons for insert with check (owner_id = auth.uid());
drop policy if exists seasons_update_owner on seasons;
create policy seasons_update_owner on seasons for update using (owner_id = auth.uid());
drop policy if exists seasons_delete_owner on seasons;
create policy seasons_delete_owner on seasons for delete using (owner_id = auth.uid());

drop policy if exists sponsors_select_any on sponsors;
create policy sponsors_select_any on sponsors for select using (true);
drop policy if exists sponsors_insert_self on sponsors;
create policy sponsors_insert_self on sponsors for insert with check (created_by = auth.uid() or created_by is null);
drop policy if exists sponsors_update_self on sponsors;
create policy sponsors_update_self on sponsors for update using (created_by = auth.uid());

drop policy if exists placements_select_public on sponsor_placements;
create policy placements_select_public on sponsor_placements for select using (exists (
  select 1 from tournaments t where t.id = sponsor_placements.tournament_id
    and (t.visibility = 'public' or t.owner_id = auth.uid())));
drop policy if exists placements_modify_owner on sponsor_placements;
create policy placements_modify_owner on sponsor_placements for all
  using (exists (select 1 from tournaments t where t.id = sponsor_placements.tournament_id and t.owner_id = auth.uid()))
  with check (exists (select 1 from tournaments t where t.id = sponsor_placements.tournament_id and t.owner_id = auth.uid()));
